server:
  port: ${custome_port:8095}
  
spring:
  main:
    allow-bean-definition-overriding: true
    banner-mode: "off"
  data:
    mongodb:
      uri: ${mongodb_url}
      database: ${mongodb_database} 
  rabbitmq:
    host: ${rabbitmq_host:localhost}
    port: ${rabbitmq_port:5672}
    username: ${rabbitmq_user:guest}
    password: ${rabbitmq_pass:guest}
  cloud:
    bus:
      enabled: ${cloud_bus:true}
      refresh:
        enabled: ${cloud_bus_refresh:true}
      id: ${spring.application.name}:${spring.profiles.active}:${random.uuid}

  codec:
    max-in-memory-size: 10MB

eureka:
  client:
    registerWithEureka: ${registerWithEureka:true}
    fetchRegistry: ${fetchRegistry:true}
    service-url:
      defaultZone:  ${eureka_url:http://localhost:8761/eureka/}

  instance:
    hostname: ${HOSTNAME:${spring.application.name}}
    preferIpAddress: ${preferIpAddress:false}
    instanceId: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}:${server.port}
    
    